name: q_task_flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^1.1.0

  # di
  injectable: ^1.5.3
  get_it: ^7.2.0

  # network
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  json_annotation: ^4.5.0

  # local storage
  floor: ^1.2.0
  sqflite: ^2.0.2+1

  # state management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  # l10n
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  infinite_scroll_pagination: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  flutter_lints: ^2.0.1
  json_serializable: ^6.2.0
  injectable_generator: any
  retrofit_generator: any
  floor_generator: ^1.2.0
  freezed: ^1.1.0
  dio_logger: ^4.0.8+8
  logger: any




flutter:
  uses-material-design: true
  generate: true

  assets:
    - config/
flutter_intl:
  enabled: true
